services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "./config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb-data:/var/lib/influxdb2"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-data:/var/lib/grafana"

  labsentinel_app:
    build: "."
    depends_on:
      - mqtt
    restart: unless-stopped
    volumes:
      - "./app-data:/app/data"